(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)




Int[1/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := x/Rt[a^2-b^2,2] - 2/(d*Rt[a^2-b^2,2])*ArcTan[Sim[b*Sin[c+d*x]/(a+Rt[a^2-b^2,2]+b*Cos[c + d*x])]] /;FreeQ[{a,b,c,d},x] && PositiveQ[a^2-b^2]


Int[1/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := 2*ArcTan[(a-b)*Tan[(c+d*x)/2]/Rt[a^2-b^2,2]]/(d*Rt[a^2-b^2,2]) /;FreeQ[{a,b,c,d},x] && PosQ[a^2-b^2]



Int[1/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := -2*ArcTanh[(a-b)*Tan[(c+d*x)/2]/Rt[b^2-a^2,2]]/(d*Rt[b^2-a^2,2]) /;FreeQ[{a,b,c,d},x] && NegQ[a^2-b^2]



Int[1/Sqrt[a_.+b_.*Cos[c_.+d_.*x_]],x_Symbol] := 2*EllipticF[(c+d*x)/2,Sim[2*b/(a+b)]]/(d*Sqrt[a+b]) /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]



Int[1/Sqrt[a_.+b_.*Cos[c_.+d_.*x_]],x_Symbol] := Sqrt[(a+b*Cos[c+d*x])/(a+b)]/Sqrt[a+b*Cos[c+d*x]]*Int[1/Sqrt[a/(a+b)+b/(a+b)*Cos[c+d*x]],x] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && Not[PositiveQ[a+b]]



Int[Sqrt[a_.+b_.*Cos[c_.+d_.*x_]],x_Symbol] := 2*Sqrt[a+b]*EllipticE[(c+d*x)/2,Sim[2*b/(a+b)]]/d /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]



Int[Sqrt[a_.+b_.*Cos[c_.+d_.*x_]],x_Symbol] := Sqrt[a+b*Cos[c+d*x]]/Sqrt[(a+b*Cos[c+d*x])/(a+b)]*Int[Sqrt[a/(a+b)+b/(a+b)*Cos[c+d*x]],x] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && Not[PositiveQ[a+b]]



Int[Sqrt[Cos[c_.+d_.*x_]]/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := Dist[1/b,Int[1/Sqrt[Cos[c+d*x]],x]] - Dist[a/b,Int[1/(Sqrt[Cos[c+d*x]]*(a+b*Cos[c+d*x])),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]



Int[Sqrt[Cos[c_.+d_.*x_]]/Sqrt[a_+b_.*Cos[c_.+d_.*x_]],x_Symbol] := Int[(1+Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] - Int[1/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := 4*A/(d*Sqrt[a+b])*EllipticPi[-1,ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A-B] && PositiveQ[b] && PositiveQ[b^2-a^2]



Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := Sqrt[-Cos[c+d*x]]/Sqrt[Cos[c+d*x]]*Int[(A+A*Cos[c+d*x])/(Sqrt[-Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A+B] && NegativeQ[b] && PositiveQ[b^2-a^2]



Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := 4*A*Sqrt[1+Cos[c+d*x]]/(d*Sqrt[a+b*Cos[c+d*x]])* Sqrt[(a+b*Cos[c+d*x])/((a+b)*(1+Cos[c+d*x]))]* EllipticPi[-1,ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A-B] && NonzeroQ[a^2-b^2]


Int[Sqrt[-Cos[c_.+d_.*x_]]/Sqrt[a_+b_.*Cos[c_.+d_.*x_]],x_Symbol] := Int[(1-Cos[c+d*x])/(Sqrt[-Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] - Int[1/(Sqrt[-Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]



Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := -4*A/(d*Sqrt[a-b])*EllipticPi[-1,ArcSin[Cot[(c+d*x)/2]],-Sim[(a+b)/(a-b)]] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A+B] && NegativeQ[b] && PositiveQ[b^2-a^2]



Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := Sqrt[Cos[c+d*x]]/Sqrt[-Cos[c+d*x]]*Int[1/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A-B] && PositiveQ[b] && PositiveQ[b^2-a^2]


Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := -4*A*Sqrt[1-Cos[c+d*x]]/(d*Sqrt[a+b*Cos[c+d*x]])* Sqrt[(a+b*Cos[c+d*x])/((a-b)*(1-Cos[c+d*x]))]* EllipticPi[-1,ArcSin[Cot[(c+d*x)/2]],-Sim[(a+b)/(a-b)]] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A+B] && NonzeroQ[a^2-b^2]



Int[Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]],x_Symbol] := Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]*Tan[(1/2)*(c+d*x)]/d + Int[Sqrt[a+b*Cos[c+d*x]]/(Sqrt[Cos[c+d*x]]*(1+Cos[c+d*x])),x] - Dist[a/2,Int[(1-Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]



Int[1/(Sqrt[Cos[c_.+d_.*x_]]*(a_+b_.*Cos[c_.+d_.*x_])),x_Symbol] := 2/(d*(a+b))*EllipticPi[Sim[2*b/(a+b)],(c+d*x)/2,2] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]



Int[1/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_.+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := 2/(d*Sqrt[a+b])*EllipticF[ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;FreeQ[{a,b,c,d},x] && PositiveQ[b] && PositiveQ[b^2-a^2]



Int[1/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := Sqrt[-Cos[c+d*x]]/Sqrt[Cos[c+d*x]]*Int[1/(Sqrt[-Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d},x] && NegativeQ[b] && PositiveQ[b^2-a^2]



Int[1/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_.+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := 2*Sqrt[1+Cos[c+d*x]]/(d*Sqrt[a+b*Cos[c+d*x]])* Sqrt[(a+b*Cos[c+d*x])/((a+b)*(1+Cos[c+d*x]))]* EllipticF[ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]



Int[1/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := -2/(d*Sqrt[a-b])*EllipticF[ArcSin[Cot[(c+d*x)/2]],-Sim[(a+b)/(a-b)]] /;FreeQ[{a,b,c,d},x] && NegativeQ[b] && PositiveQ[b^2-a^2]



Int[1/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := Sqrt[Cos[c+d*x]]/Sqrt[-Cos[c+d*x]]*Int[1/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d},x] && PositiveQ[b] && PositiveQ[b^2-a^2]



Int[1/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := -2*Sqrt[1-Cos[c+d*x]]/(d*Sqrt[a+b*Cos[c+d*x]])* Sqrt[(a+b*Cos[c+d*x])/((a-b)*(1-Cos[c+d*x]))]* EllipticF[ArcSin[Cot[(c+d*x)/2]],-Sim[(a+b)/(a-b)]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]



Int[Sqrt[a_+b_.*Cos[c_.+d_.*x_]]/Sqrt[Cos[c_.+d_.*x_]],x_Symbol] := Dist[a-b,Int[1/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]] + Dist[b,Int[(1+Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


Int[Sqrt[a_+b_.*Cos[c_.+d_.*x_]]/(Sqrt[Cos[c_.+d_.*x_]]*(A_+B_.*Cos[c_.+d_.*x_])),x_Symbol] := Sqrt[a+b]/(d*A)*EllipticE[ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A-B] && PositiveQ[b] && PositiveQ[b^2-a^2]



(* Int[Sqrt[a_+b_.*Cos[c_.+d_.*x_]]/(Sqrt[Cos[c_.+d_.*x_]]*(A_+B_.*Cos[c_.+d_.*x_])),x_Symbol] := Sqrt[-Cos[c+d*x]]/Sqrt[Cos[c+d*x]]*Int[(A+A*Cos[c+d*x])/(Sqrt[-Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A+B] && NegativeQ[b] && PositiveQ[b^2-a^2] *)



Int[Sqrt[a_+b_.*Cos[c_.+d_.*x_]]/(Sqrt[Cos[c_.+d_.*x_]]*(A_+B_.*Cos[c_.+d_.*x_])),x_Symbol] := Sqrt[a+b*Cos[c+d*x]]/(d*A*Sqrt[1+Cos[c+d*x]]*Sqrt[(a+b*Cos[c+d*x])/((a+b)*(1+Cos[c+d*x]))])* EllipticE[ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A-B] && NonzeroQ[a^2-b^2]



Int[Cos[c_.+d_.*x_]^(3/2)/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := Dist[1/b,Int[Sqrt[Cos[c+d*x]],x]] - Dist[a/b,Int[Sqrt[Cos[c+d*x]]/(a+b*Cos[c+d*x]),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]



Int[Cos[c_.+d_.*x_]^(3/2)/Sqrt[a_+b_.*Cos[c_.+d_.*x_]],x_Symbol] := Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]*Tan[(c+d*x)/2]/(b*d) + Dist[1/b,Int[Sqrt[a+b*Cos[c+d*x]]/(Sqrt[Cos[c+d*x]]*(1+Cos[c+d*x])),x]] - Dist[a/(2*b),Int[(1+Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]



Int[Cos[a_.+b_.*x_],x_Symbol] := Sin[a+b*x]/b /;FreeQ[{a,b},x]



Int[Cos[a_.+b_.*x_]^n_,x_Symbol] := Dist[1/b,ReplaceAll[Int[Expand[(1-x^2)^((n-1)/2),x],x],x->Sin[a+b*x]]] /;FreeQ[{a,b},x] && OddQ[n] && n>1;



Int[(b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := b*Sin[c+d*x]*(b*Cos[c+d*x])^(n-1)/(d*n) + Dist[(n-1)*b^2/n,Int[(b*Cos[c+d*x])^(n-2),x]] /;FreeQ[{b,c,d},x] && RationalQ[n] && n>1 && Not[OddQ[n]]



Int[(b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -Sin[c+d*x]*(b*Cos[c+d*x])^(n+1)/(b*d*(n+1)) + Dist[(n+2)/((n+1)*b^2),Int[(b*Cos[c+d*x])^(n+2),x]] /;FreeQ[{b,c,d},x] && RationalQ[n] && n<-1;



Int[(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := b*Sin[c+d*x]*(a+b*Cos[c+d*x])^(n+1)/(d*(n+1)*(a^2-b^2)) + Dist[1/((n+1)*(a^2-b^2)),Int[(a*(n+1)-b*(n+2)*Cos[c+d*x])*(a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[n] && n<-1;



Int[(a_+b_.*Cos[c_.+d_.*x_])^2,x_Symbol] := (2*a^2+b^2)*x/2 + 2*a*b*Sin[c+d*x]/d + b^2*Cos[c+d*x]*Sin[c+d*x]/(2*d) /;FreeQ[{a,b,c,d},x]



Int[(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := b*Sin[c+d*x]*(a+b*Cos[c+d*x])^(n-1)/(d*n) + Dist[1/n,Int[Sim[a^2*n+b^2*(n-1)+a*b*(2*n-1)*Cos[c+d*x],x]*(a+b*Cos[c+d*x])^(n-2),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[n] && n>=3/2 && n!=2;



Int[Cos[c_.+d_.*x_]^m_*(a_+b_.*Cos[c_.+d_.*x_])^2,x_Symbol] := -a^2*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+1)) + Dist[1/(m+1),Int[Cos[c+d*x]^(m+1)*(2*a*b*(m+1)+(a^2*(m+2)+b^2*(m+1))*Cos[c+d*x]),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m<-1;



Int[Cos[c_.+d_.*x_]^m_.*(a_+b_.*Cos[c_.+d_.*x_])^2,x_Symbol] := b^2*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+2)) + Dist[1/(m+2),Int[Cos[c+d*x]^m*(a^2*(m+2)+b^2*(m+1)+2*a*b*(m+2)*Cos[c+d*x]),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[m] && m>=-1;



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := a^2*Sin[c+d*x]*Cos[c+d*x]^(m-2)*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+1)*(a^2-b^2)) + Dist[1/(b*(n+1)*(a^2-b^2)), Int[Cos[c+d*x]^(m-3)* Sim[a^2*(m-2)+a*b*(n+1)*Cos[c+d*x]-(a^2*(m-1)+b^2*(n+1))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m>2 && n<-1;



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -a*Sin[c+d*x]*Cos[c+d*x]^(m-1)*(a+b*Cos[c+d*x])^(n+1)/(d*(n+1)*(a^2-b^2)) + Dist[1/((n+1)*(a^2-b^2)), Int[Cos[c+d*x]^(m-2)* Sim[-a*(m-1)-b*(n+1)*Cos[c+d*x]+a*(m+n+1)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && 1<m<2 && n<-1;



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := b*Sin[c+d*x]*Cos[c+d*x]^m*(a+b*Cos[c+d*x])^(n+1)/(d*(n+1)*(a^2-b^2)) + Dist[1/((n+1)*(a^2-b^2)), Int[Cos[c+d*x]^(m-1)* Sim[b*m+a*(n+1)*Cos[c+d*x]-b*(m+n+2)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && 0<m<1 && n<-1;



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := Sin[c+d*x]*Cos[c+d*x]^(m-2)*(a+b*Cos[c+d*x])^(n+1)/(b*d*(m+n)) + Dist[1/(b*(m+n)), Int[Cos[c+d*x]^(m-3)* Sim[a*(m-2)+b*(m+n-1)*Cos[c+d*x]-a*(m-1)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m>2 && -1<=n<0;



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := Sin[c+d*x]*Cos[c+d*x]^(m-1)*(a+b*Cos[c+d*x])^n/(d*(m+n)) + Dist[1/(m+n), Int[Cos[c+d*x]^(m-2)* Sim[a*(m-1)+b*(m+n-1)*Cos[c+d*x]+a*n*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-1),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m>1 && m!=2 && 0<n<1;



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := b^2*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n-2)/(d*(m+n)) + Dist[1/(m+n), Int[Cos[c+d*x]^m* Sim[a*(b^2*(m+1)+a^2*(m+n))+b*(3*a^2*(m+n)+b^2*(m+n-1))*Cos[c+d*x]+ a*b^2*(2*m+3*n-2)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-3),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m>-1 && m!=2 && n>2;



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := b*Sin[c+d*x]*Cos[c+d*x]^m*(a+b*Cos[c+d*x])^(n-1)/(d*(m+n)) + Dist[1/(m+n), Int[Cos[c+d*x]^(m-1)* Sim[a*b*m+(a^2*(m+n)+b^2*(m+n-1))*Cos[c+d*x]+(a*b*(m+n)+a*b*(n-1))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-2),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m>0 && m!=2 && 1<n<2;



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -a^2*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n-2)/(d*(m+1)) + Dist[1/(m+1), Int[Cos[c+d*x]^(m+1)* (a^2*b*(2*m-n+4)+a*(3*b^2*(m+1)+a^2*(m+2))*Cos[c+d*x]+b*(b^2*(m+1)+a^2*(m+n))*Cos[c+d*x]^2)* (a+b*Cos[c+d*x])^(n-3),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m<-1 && n>2



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -a*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n-1)/(d*(m+1)) + Dist[1/(m+1), Int[Cos[c+d*x]^(m+1)* Sim[a*b*(m-n+2)+(b^2*(m+1)+a^2*(m+2))*Cos[c+d*x]+a*b*(m+n+1)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-2),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m<0 && m!=-1 && 1<n<2;



Int[Cos[c_.+d_.*x_]^m_*(a_.+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^n/(d*(m+1)) + Dist[1/(m+1), Int[Cos[c+d*x]^(m+1)* Sim[-b*n+a*(m+2)*Cos[c+d*x]+b*(m+n+2)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-1),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m<-1 && 0<n<1



Int[Cos[c_.+d_.*x_]^m_*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n+1)/(a*d*(m+1)) + Dist[1/(a*(m+1)), Int[Cos[c+d*x]^(m+1)* Sim[-b*(m+n+2)+a*(m+2)*Cos[c+d*x]+b*(m+n+3)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m<-1 && -1<=n<0;


Int[Cos[c_.+d_.*x_]^m_*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -b^2*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n+1)/(a*d*(n+1)*(a^2-b^2)) + Dist[1/(a*(n+1)*(a^2-b^2)), Int[Cos[c+d*x]^m* Sim[a^2*(n+1)-b^2*(m+n+2)-a*b*(n+1)*Cos[c+d*x]+(m+n+3)*(b^2)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m<0 && n<-1


Int[Sqrt[Cos[c_.+d_.*x_]]*(A_+B_.*Cos[c_.+d_.*x_]),x_Symbol] := Dist[A,Int[Sqrt[Cos[c+d*x]],x]] + Dist[B,Int[Cos[c+d*x]^(3/2),x]] /;FreeQ[{c,d,A,B},x]



Int[(A_+B_.*Cos[c_.+d_.*x_])/Sqrt[Cos[c_.+d_.*x_]],x_Symbol] := Dist[A,Int[1/Sqrt[Cos[c+d*x]],x]] + Dist[B,Int[Sqrt[Cos[c+d*x]],x]] /;FreeQ[{c,d,A,B},x]



Int[(A_.+B_.*Cos[c_.+d_.*x_])/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := B*x/b + Dist[(b*A-a*B)/b,Int[1/(a+b*Cos[c+d*x]),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[b*A-a*B]



Int[(A_.+B_.*Cos[c_.+d_.*x_])/Sqrt[a_+b_.*Cos[c_.+d_.*x_]],x_Symbol] := Dist[B/b,Int[Sqrt[a+b*Cos[c+d*x]],x]] +  Dist[(b*A-a*B)/b,Int[1/Sqrt[a+b*Cos[c+d*x]],x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[b*A-a*B]



Int[Sqrt[Cos[c_.+d_.*x_]]*(A_+B_.*Cos[c_.+d_.*x_])/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := Dist[B/b,Int[Sqrt[Cos[c+d*x]],x]] + Dist[(b*A-a*B)/b,Int[Sqrt[Cos[c+d*x]]/(a+b*Cos[c+d*x]),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B]


Int[Sqrt[Cos[c_.+d_.*x_]]*(A_+B_.*Cos[c_.+d_.*x_])/Sqrt[a_+b_.*Cos[c_.+d_.*x_]],x_Symbol] := Int[(A*Cos[c+d*x]+B*Cos[c+d*x]^2)/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B]



Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[Cos[c_.+d_.*x_]]*(a_+b_.*Cos[c_.+d_.*x_])),x_Symbol] := B/b*Int[1/Sqrt[Cos[c+d*x]],x] +  (b*A-a*B)/b*Int[1/(Sqrt[Cos[c+d*x]]*(a+b*Cos[c+d*x])),x] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B]



Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := B*Int[(1+Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]+(A-B)*Int[1/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[A-B]



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_]),x_Symbol] := -A*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+1)) + Disst[1/(m+1),Int[Cos[c+d*x]^(m+1)*(B*(m+1)+A*(m+2)*Cos[c+d*x]),x]] /;FreeQ[{c,d,A,B},x] && RationalQ[m] && m<-1;



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_]),x_Symbol] := B*Sin[c+d*x]*Cos[c+d*x]^m/(d*(m+1)) +  Dist[1/(m+1),Int[Cos[c+d*x]^(m-1)*(B*m+A*(m+1)*Cos[c+d*x]),x]] /;FreeQ[{c,d,A,B},x] && RationalQ[m] && m>1;


Int[(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := Dist[B/b,Int[(a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B,n},x] && ZeroQ[b*A-a*B]


Int[(A_.+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := (b*A-a*B)*Sin[c+d*x]*(a+b*Cos[c+d*x])^(n+1)/(d*(n+1)*(a^2-b^2)) + Dist[1/((n+1)*(a^2-b^2)), Int[Sim[(n+1)*(a*A-b*B)-(n+2)*(b*A-a*B)*Cos[c+d*x],x]*(a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[b*A-a*B] && NonzeroQ[a^2-b^2] && RationalQ[n] && n<-1/2 && n!=-1;



Int[(A_.+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := (2*a*A+b*B)*x/2+(A*b+a*B)*Sin[c+d*x]/d+b*B*Cos[c+d*x]*Sin[c+d*x]/(2*d) /;FreeQ[{a,b,c,d,A,B},x]

(*(2*a*A+b*B)*x/2+(2*b*A+2*a*B+b*B*Cos[c+d*x])*(Sin[c+d*x]/(2*d)) /; *)


Int[(A_.+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := B*Sin[c+d*x]*(a+b*Cos[c+d*x])^n/(d*(n+1)) +  Dist[1/(n+1),Int[Sim[b*B*n+a*A*(n+1)+(a*B*n+b*A*(n+1))*Cos[c+d*x],x]*(a+b*Cos[c+d*x])^(n-1),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[b*A-a*B] && NonzeroQ[a^2-b^2] && RationalQ[n] && n>=1/2;



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := -a*A*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+1)) +  Dist[1/(m+1),Int[Cos[c+d*x]^(m+1)*((b*A+a*B)*(m+1)+(a*A*(m+2)+b*B*(m+1))*Cos[c+d*x]),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[m] && m<-1;



Int[Cos[c_.+d_.*x_]^m_.*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] := b*B*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+2)) +  Dist[1/(m+2),Int[Cos[c+d*x]^m*Sim[a*A*(m+2)+b*B*(m+1)+(b*A+a*B)*(m+2)*Cos[c+d*x],x],x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[m] && m>=-1;


Int[Cos[c_.+d_.*x_]*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -a*(b*A-a*B)*Sin[c+d*x]*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+1)*(a^2-b^2)) - Dist[1/(b*(n+1)*(a^2-b^2)), Int[Sim[b*(n+1)* (b*A-a*B)+(a^2*B-a*b*A*(n+2)+b^2*B*(n+1))*Cos[c+d*x],x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[n] && n<-1;



Int[Cos[c_.+d_.*x_]*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := B*Sin[c+d*x]*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+2)) + Dist[1/(b*(n+2)),Int[Sim[b*B*(n+1)-(a*B-b*A*(n+2))*Cos[c+d*x],x]*(a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[n] && n>=-1;



Int[Cos[c_.+d_.*x_]^m_.*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := Dist[B/b,Int[Cos[c+d*x]^m*(a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B,m,n},x] && ZeroQ[b*A-a*B]



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -a*(b*A-a*B)*Sin[c+d*x]*Cos[c+d*x]^(m-1)*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+1)*(a^2-b^2)) - Dist[1/(b*(n+1)*(a^2-b^2)), Int[Cos[c+d*x]^(m-2)* Sim[a*(m-1)*(b*A-a*B)+b*(n+1)*(b*A-a*B)*Cos[c+d*x]+(a^2*B*m-a*b*A*(m+n+1)+ b^2*B*(n+1))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[{m,n}] && m>1 && n<-1/2 && n!=-1


Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := (b*A-a*B)*Sin[c+d*x]*Cos[c+d*x]^m*(a+b*Cos[c+d*x])^(n+1)/(d*(n+1)*(a^2-b^2)) + Dist[1/((n+1)*(a^2-b^2)), Int[Cos[c+d*x]^(m-1)* Sim[m*(b*A-a*B)+(n+1)*(a*A-b*B)*Cos[c+d*x]-(b*A-a*B)*(m+n+2)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[{m,n}] && 0<m<1 && n<-1/2 && n!=-1


Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := B*Sin[c+d*x]*Cos[c+d*x]^(m-1)*(a+b*Cos[c+d*x])^(n+1)/(b*d*(m+n+1)) + Dist[1/(b*(m+n+1)), Int[Cos[c+d*x]^(m-2)* Sim[a*B*(m-1)+b*B*(m+n)*Cos[c+d*x]+(b*A*(m+n+1)-a*B*m)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[{m,n}] && m>1 && (-1/2<=n<1/2 || n==-1)



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := b*B*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n-1)/(d*(m+n+1)) + Dist[1/(m+n+1), Int[Cos[c+d*x]^m* Sim[a*(b*B*(m+1)+a*A*(m+n+1))+(b^2*B*(m+n)+a*(2*A*b+a*B)*(m+n+1))*Cos[c+d*x]+ b*(A*b*(m+n+1)+a*B*(m+2*n))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-2),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[{m,n}] && m>=-1 && n>=3/2



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := B*Sin[c+d*x]*Cos[c+d*x]^m*(a+b*Cos[c+d*x])^n/(d*(m+n+1)) + Dist[1/(m+n+1), Int[Cos[c+d*x]^(m-1)* Sim[a*B*m+(a*A*(m+n+1)+b*B*(m+n))*Cos[c+d*x]+(b*A*(m+n+1)+a*B*n)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-1),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[{m,n}] && m>0 && 1/2<=n<3/2



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -a*A*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n-1)/(d*(m+1)) + Dist[1/(m+1), Int[Cos[c+d*x]^(m+1)* Sim[a*((b*A+a*B)*(m+1)-b*A*(n-1))+(b*(b*A+2*a*B)*(m+1)+a^2*A*(m+2))*Cos[c+d*x]+ b*(b*B*(m+1)+a*A*(m+n+1))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-2),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[{m,n}] && m<-1 && n>=3/2



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := -A*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^n/(d*(m+1)) + Dist[1/(m+1), Int[Cos[c+d*x]^(m+1)* Sim[a*B*(m+1)-b*A*n+(b*B*(m+1)+a*A*(m+2))*Cos[c+d*x]+b*A*(m+n+2)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-1),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[{m,n}] && m<0 && m!=-1 && 1/2<=n<3/2


Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -A*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n+1)/(a*d*(m+1)) + Dist[1/(a*(m+1)), Int[Cos[c+d*x]^(m+1)* Sim[a*B*(m+1)-b*A*(m+n+2)+a*A*(m+2)*Cos[c+d*x]+b*A*(m+n+3)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[{m,n}] && m<-1 && (-1/2<=n<1/2 || n==-1)



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_])*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -b*(b*A-a*B)*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n+1)/(a*d*(n+1)*(a^2-b^2)) + Dist[1/(a*(n+1)*(a^2-b^2)), Int[Cos[c+d*x]^m* Sim[A*(a^2*(n+1)-b^2*(m+n+2))+a*b*B*(m+1)-a*(n+1)*(b*A-a*B)*Cos[c+d*x]+ b*(b*A-a*B)*(m+n+3)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B},x] && NonzeroQ[a^2-b^2] && NonzeroQ[b*A-a*B] && RationalQ[{m,n}] && m<0 && n<-1/2 && n!=-1


Int[(A_+C_.*Cos[c_.+d_.*x_]^2)/(Sqrt[Cos[c_.+d_.*x_]]*(a_+b_.*Cos[c_.+d_.*x_])),x_Symbol] := Dist[C/b,Int[Sqrt[Cos[c+d*x]],x]] + Dist[1/b,Int[(A*b-a*C*Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*(a+b*Cos[c+d*x])),x]] /;FreeQ[{a,b,c,d,A,C},x] && NonzeroQ[a^2-b^2]

Int[(A_+C_.*Cos[c_.+d_.*x_]^2)/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := C*Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]*Tan[(c+d*x)/2]/(b*d) + Dist[C/b,Int[Sqrt[a+b*Cos[c+d*x]]/(Sqrt[Cos[c+d*x]]*(1+Cos[c+d*x])),x]] + Dist[1/(2*b),Int[(2*A*b-a*C-a*C*Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]] /;FreeQ[{a,b,c,d,A,C},x] && NonzeroQ[a^2-b^2]


Int[Cos[c_.+d_.*x_]^m_.*(A_+C_.*Cos[c_.+d_.*x_]^2),x_Symbol] := C*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+2)) /;FreeQ[{c,d,A,C,m},x] && ZeroQ[A*(m+2)+C*(m+1)]


Int[Cos[c_.+d_.*x_]^m_*(A_+C_.*Cos[c_.+d_.*x_]^2),x_Symbol] := -A*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+1)) + Dist[(A*(m+2)+C*(m+1))/(m+1),Int[Cos[c+d*x]^(m+2),x]] /;FreeQ[{c,d,A,C},x] && NonzeroQ[A*(m+2)+C*(m+1)] && RationalQ[m] && m<-1


Int[Cos[c_.+d_.*x_]^m_.*(A_+C_.*Cos[c_.+d_.*x_]^2),x_Symbol] := C*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+2)) + Dist[(A*(m+2)+C*(m+1))/(m+2),Int[Cos[c+d*x]^m,x]] /;FreeQ[{c,d,A,C},x] && NonzeroQ[A*(m+2)+C*(m+1)] && RationalQ[m] && m>=-1


Int[(A_+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := -Dist[C/b^2,Int[(a-b*Cos[c+d*x])*(a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,C},x] && ZeroQ[a^2*C+b^2*A] && RationalQ[n] && n<-1



Int[(A_.+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := (a^2*C+b^2*A)*Sin[c+d*x]*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+1)*(a^2-b^2)) + Dist[1/(b*(n+1)*(a^2-b^2)), Int[Sim[a*b*(A+C)*(n+1)-(b^2*A*(n+2)+C*(a^2+b^2*(n+1)))*Cos[c+d*x],x]*(a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,C},x] && NonzeroQ[a^2-b^2] && NonzeroQ[a^2*C+b^2*A] && RationalQ[n] && n<-1


Int[(A_.+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := C*Sin[c+d*x]*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+2)) + Dist[1/(b*(n+2)), Int[Sim[b*(A*(n+2)+C*(n+1))-a*C*Cos[c+d*x],x]*(a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d,A,C},x] && RationalQ[n] && n>=-1


Int[Cos[c_.+d_.*x_]^m_.*(A_+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := Dist[C/b^2,Int[Cos[c+d*x]^m*(-a+b*Cos[c+d*x])*(a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,C,m},x] && ZeroQ[a^2*C+b^2*A] && RationalQ[n] && n<-1/2


Int[Cos[c_.+d_.*x_]^m_.*(A_+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := (a^2*C+b^2*A)*Sin[c+d*x]*Cos[c+d*x]^m*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+1)*(a^2-b^2)) + Dist[1/(b*(n+1)*(a^2-b^2)), Int[Cos[c+d*x]^(m-1)* Sim[m*(a^2*C+b^2*A)+a*b*(n+1)*(C+A)*Cos[c+d*x]- (a^2*C*(m+1)+b^2*(A*(m+n+2)+C*(n+1)))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,C},x] && NonzeroQ[a^2-b^2] && NonzeroQ[a^2*C+b^2*A] && RationalQ[{m,n}] && m>0 && n<-1/2 && n!=-1



Int[Cos[c_.+d_.*x_]^m_.*(A_+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := C*Sin[c+d*x]*Cos[c+d*x]^m*(a+b*Cos[c+d*x])^(n+1)/(b*d*(m+n+2)) + Dist[1/(b*(m+n+2)), Int[Cos[c+d*x]^(m-1)* Sim[a*C*m+(b*A*(m+n+2)+b*C*(m+n+1))*Cos[c+d*x]-a*C*(m+1)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d,A,C},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m>0 && (-1/2<=n<1/2 || n==-1)



Int[Cos[c_.+d_.*x_]^m_.*(A_+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := C*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^n/(d*(m+n+2)) + Dist[1/(m+n+2), Int[Cos[c+d*x]^m* Sim[a*(A*(m+n+2)+C*(m+1))+(b*A*(m+n+2)+b*C*(m+n+1))*Cos[c+d*x]+ a*C*n*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-1),x]] /;FreeQ[{a,b,c,d,A,C},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m>=-1 && n>=1/2



Int[Cos[c_.+d_.*x_]^m_*(A_+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := -A*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^n/(d*(m+1)) + Dist[1/(m+1), Int[Cos[c+d*x]^(m+1)* Sim[-b*A*n+(a*C*(m+1)+a*A*(m+2))*Cos[c+d*x]+b*(C*(m+1)+A*(m+n+2))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-1),x]] /;FreeQ[{a,b,c,d,A,C},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m<-1 && n>=1/2



Int[Cos[c_.+d_.*x_]^m_*(A_+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -A*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n+1)/(a*d*(m+1)) + Dist[1/(a*(m+1)), Int[Cos[c+d*x]^(m+1)* Sim[-b*A*(m+n+2)+a*(A*(m+2)+C*(m+1))*Cos[c+d*x]+b*A*(m+n+3)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d,A,C},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m<-1 && (-1/2<=n<1/2 || n==-1)



Int[Cos[c_.+d_.*x_]^m_*(A_+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -(a^2*C+b^2*A)*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n+1)/(a*d*(n+1)*(a^2-b^2)) + Dist[1/(a*(n+1)*(a^2-b^2)), Int[Cos[c+d*x]^m* Sim[A*(a^2*(n+1)-b^2*(m+n+2))-a^2*C*(m+1)-a*(n+1)*(b*A+b*C)*Cos[c+d*x]+ (m+n+3)*(a^2*C+b^2*A)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,C},x] && NonzeroQ[a^2-b^2] && NonzeroQ[a^2*C+b^2*A] && RationalQ[{m,n}] && m<0 && n<-1/2 && n!=-1



Int[(A_+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)/(Sqrt[Cos[c_.+d_.*x_]]*(a_+b_.*Cos[c_.+d_.*x_])),x_Symbol] := Dist[C/b,Int[Sqrt[Cos[c+d*x]],x]] + Dist[1/b,Int[(A*b+(b*B-a*C)*Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*(a+b*Cos[c+d*x])),x]] /;FreeQ[{a,b,c,d,A,B,C},x] && NonzeroQ[a^2-b^2]


Int[(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] := C*Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]*Tan[(c+d*x)/2]/(b*d) + Dist[C/b,Int[Sqrt[a+b*Cos[c+d*x]]/(Sqrt[Cos[c+d*x]]*(1+Cos[c+d*x])),x]] + Dist[1/(2*b),Int[(2*A*b-a*C+(2*b*B-a*C)*Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]] /;FreeQ[{a,b,c,d,A,B,C},x] && NonzeroQ[a^2-b^2]



Int[Cos[c_.+d_.*x_]^m_.*(B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2),x_Symbol] := Int[Cos[c+d*x]^(m+1)*(B+C*Cos[c+d*x]),x] /;FreeQ[{c,d,B,C},x] && RationalQ[m] && m<=-1


Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2),x_Symbol] := -A*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+1)) + Dist[1/(m+1),Int[Cos[c+d*x]^(m+1)*Sim[B*(m+1)+(A*(m+2)+C*(m+1))*Cos[c+d*x],x],x]] /;FreeQ[{c,d,A,B,C},x] && RationalQ[m] && m<-1



Int[Cos[c_.+d_.*x_]^m_.*(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2),x_Symbol] := C*Sin[c+d*x]*Cos[c+d*x]^(m+1)/(d*(m+2)) + Dist[1/(m+2),Int[Cos[c+d*x]^m*Sim[A*(m+2)+C*(m+1)+B*(m+2)*Cos[c+d*x],x],x]] /;FreeQ[{c,d,A,B,C},x] && RationalQ[m] && m>=-1



Int[(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := Dist[1/b^2,Int[Sim[b*B-a*C+b*C*Cos[c+d*x],x]*(a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B,C},x] && ZeroQ[a^2*C-a*b*B+b^2*A] && RationalQ[n] && n<-1



Int[(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := (a^2*C-a*b*B+b^2*A)*Sin[c+d*x]*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+1)*(a^2-b^2)) + Dist[1/(b*(n+1)*(a^2-b^2)), Int[Sim[b*(a*(A+C)-b*B)*(n+1)-(b*(b*A-a*B)*(n+2)+C*(a^2+b^2*(n+1)))*Cos[c+d*x],x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B,C},x] && NonzeroQ[a^2-b^2] && NonzeroQ[a^2*C-a*b*B+b^2*A] && RationalQ[n] && n<-1


Int[(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := C*Sin[c+d*x]*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+2)) + Dist[1/(b*(n+2)), Int[Sim[b*(A*(n+2)+C*(n+1))+(b*B*(n+2)-a*C)*Cos[c+d*x],x]*(a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d,A,B,C},x] && RationalQ[n] && n>=-1


Int[Cos[c_.+d_.*x_]^m_.*(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := Dist[1/b^2,Int[Cos[c+d*x]^m*Sim[b*B-a*C+b*C*Cos[c+d*x],x]*(a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B,C,m},x] && ZeroQ[a^2*C-a*b*B+b^2*A] && RationalQ[n] && n<-1/2


Int[Cos[c_.+d_.*x_]^m_.*(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := (a^2*C-a*b*B+b^2*A)*Sin[c+d*x]*Cos[c+d*x]^m*(a+b*Cos[c+d*x])^(n+1)/(b*d*(n+1)*(a^2-b^2))+ Dist[1/(b*(n+1)*(a^2-b^2)), Int[Cos[c+d*x]^(m-1)* Sim[m*(a^2*C-a*b*B+b^2*A)+b*(n+1)*(a*(C+A)-b*B)*Cos[c+d*x]- (a^2*C*(m+1)-a*b*B*(m+n+2)+b^2*(A*(m+n+2)+C*(n+1)))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B,C},x] && NonzeroQ[a^2-b^2] && NonzeroQ[a^2*C-a*b*B+b^2*A] && RationalQ[{m,n}] && m>0 && n<-1/2 && n!=-1


Int[Cos[c_.+d_.*x_]^m_.*(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := C*Sin[c+d*x]*Cos[c+d*x]^m*(a+b*Cos[c+d*x])^(n+1)/(b*d*(m+n+2)) + Dist[1/(b*(m+n+2)), Int[Cos[c+d*x]^(m-1)* Sim[a*C*m+b*(A*(m+n+2)+C*(m+n+1))*Cos[c+d*x]+(b*B*(m+n+2)-a*C*(m+1))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d,A,B,C},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m>0 && (-1/2<=n<1/2 || n==-1)


Int[Cos[c_.+d_.*x_]^m_.*(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := C*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^n/(d*(m+n+2)) + Dist[1/(m+n+2), Int[Cos[c+d*x]^m* Sim[a*(A*(m+n+2)+C*(m+1))+((b*A+a*B)*(m+n+2)+b*C*(m+n+1))*Cos[c+d*x]+ (b*B*(m+n+2)+a*C*n)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-1),x]] /;FreeQ[{a,b,c,d,A,B,C},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m>=-1 && n>=1/2



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_.,x_Symbol] := -A*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^n/(d*(m+1)) + Dist[1/(m+1), Int[Cos[c+d*x]^(m+1)* Sim[a*B*(m+1)-b*A*n+((a*C+b*B)*(m+1)+a*A*(m+2))*Cos[c+d*x]+b*(C*(m+1)+A*(m+n+2))*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n-1),x]] /;FreeQ[{a,b,c,d,A,B,C},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m<-1 && n>=1/2



Int[Cos[c_.+d_.*x_]^m_*(A_+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -A*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n+1)/(a*d*(m+1)) + Dist[1/(a*(m+1)), Int[Cos[c+d*x]^(m+1)* Sim[a*B*(m+1)-b*A*(m+n+2)+a*(A*(m+2)+C*(m+1))*Cos[c+d*x]+b*A*(m+n+3)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^n,x]] /;FreeQ[{a,b,c,d,A,B,C},x] && NonzeroQ[a^2-b^2] && RationalQ[{m,n}] && m<-1 && (-1/2<=n<1/2 || n==-1)



Int[Cos[c_.+d_.*x_]^m_*(A_.+B_.*Cos[c_.+d_.*x_]+C_.*Cos[c_.+d_.*x_]^2)*(a_+b_.*Cos[c_.+d_.*x_])^n_,x_Symbol] := -(a^2*C-a*b*B+b^2*A)*Sin[c+d*x]*Cos[c+d*x]^(m+1)*(a+b*Cos[c+d*x])^(n+1)/(a*d*(n+1)*(a^2-b^2)) + Dist[1/(a*(n+1)*(a^2-b^2)), Int[Cos[c+d*x]^m* Sim[A*(a^2*(n+1)-b^2*(m+n+2))-a*(a*C-b*B)*(m+1)-a*(n+1)*(b*A-a*B+b*C)*Cos[c+d*x]+ (m+n+3)*(a^2*C-a*b*B+b^2*A)*Cos[c+d*x]^2,x]* (a+b*Cos[c+d*x])^(n+1),x]] /;FreeQ[{a,b,c,d,A,B,C},x] && NonzeroQ[a^2-b^2] && NonzeroQ[a^2*C-a*b*B+b^2*A] && RationalQ[{m,n}] && m<0 && n<-1/2 && n!=-1;


