(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[1/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] :=
  x/Rt[a^2-b^2,2] - 2/(d*Rt[a^2-b^2,2])*ArcTan[Sim[b*Sin[c+d*x]/(a+Rt[a^2-b^2,2]+b*Cos[c + d*x])]] /;
FreeQ[{a,b,c,d},x] && PositiveQ[a^2-b^2]


(* ::Code:: *)
Int[1/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] :=
  2*ArcTan[(a-b)*Tan[(c+d*x)/2]/Rt[a^2-b^2,2]]/(d*Rt[a^2-b^2,2]) /;
FreeQ[{a,b,c,d},x] && PosQ[a^2-b^2]


(* ::Code:: *)
Int[1/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] :=
  -2*ArcTanh[(a-b)*Tan[(c+d*x)/2]/Rt[b^2-a^2,2]]/(d*Rt[b^2-a^2,2]) /;
FreeQ[{a,b,c,d},x] && NegQ[a^2-b^2]


(* ::Code:: *)
Int[1/Sqrt[a_.+b_.*Cos[c_.+d_.*x_]],x_Symbol] :=
  2*EllipticF[(c+d*x)/2,Sim[2*b/(a+b)]]/(d*Sqrt[a+b]) /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]


(* ::Code:: *)
Int[1/Sqrt[a_.+b_.*Cos[c_.+d_.*x_]],x_Symbol] :=
  Sqrt[(a+b*Cos[c+d*x])/(a+b)]/Sqrt[a+b*Cos[c+d*x]]*Int[1/Sqrt[a/(a+b)+b/(a+b)*Cos[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && Not[PositiveQ[a+b]]


(* ::Code:: *)
Int[Sqrt[a_.+b_.*Cos[c_.+d_.*x_]],x_Symbol] :=
  2*Sqrt[a+b]*EllipticE[(c+d*x)/2,Sim[2*b/(a+b)]]/d /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && PositiveQ[a+b]


(* ::Code:: *)
Int[Sqrt[a_.+b_.*Cos[c_.+d_.*x_]],x_Symbol] :=
  Sqrt[a+b*Cos[c+d*x]]/Sqrt[(a+b*Cos[c+d*x])/(a+b)]*Int[Sqrt[a/(a+b)+b/(a+b)*Cos[c+d*x]],x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2] && Not[PositiveQ[a+b]]


(* ::Code:: *)
Int[Sqrt[Cos[c_.+d_.*x_]]/(a_+b_.*Cos[c_.+d_.*x_]),x_Symbol] :=
  Dist[1/b,Int[1/Sqrt[Cos[c+d*x]],x]] - 
  Dist[a/b,Int[1/(Sqrt[Cos[c+d*x]]*(a+b*Cos[c+d*x])),x]] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[Cos[c_.+d_.*x_]]/Sqrt[a_+b_.*Cos[c_.+d_.*x_]],x_Symbol] :=
  Int[(1+Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] - 
  Int[1/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=
  4*A/(d*Sqrt[a+b])*EllipticPi[-1,ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;
FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A-B] && PositiveQ[b] && PositiveQ[b^2-a^2]


(* ::Code:: *)
Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=
  Sqrt[-Cos[c+d*x]]/Sqrt[Cos[c+d*x]]*Int[(A+A*Cos[c+d*x])/(Sqrt[-Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;
FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A+B] && NegativeQ[b] && PositiveQ[b^2-a^2]


(* ::Code:: *)
Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=
  4*A*Sqrt[1+Cos[c+d*x]]/(d*Sqrt[a+b*Cos[c+d*x]])*
  Sqrt[(a+b*Cos[c+d*x])/((a+b)*(1+Cos[c+d*x]))]*
  EllipticPi[-1,ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;
FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A-B] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[-Cos[c_.+d_.*x_]]/Sqrt[a_+b_.*Cos[c_.+d_.*x_]],x_Symbol] :=
  Int[(1-Cos[c+d*x])/(Sqrt[-Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] - 
  Int[1/(Sqrt[-Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=
  -4*A/(d*Sqrt[a-b])*EllipticPi[-1,ArcSin[Cot[(c+d*x)/2]],-Sim[(a+b)/(a-b)]] /;
FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A+B] && NegativeQ[b] && PositiveQ[b^2-a^2]


(* ::Code:: *)
Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=
  Sqrt[Cos[c+d*x]]/Sqrt[-Cos[c+d*x]]*Int[1/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;
FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A-B] && PositiveQ[b] && PositiveQ[b^2-a^2]


(* ::Code:: *)
Int[(A_+B_.*Cos[c_.+d_.*x_])/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=
  -4*A*Sqrt[1-Cos[c+d*x]]/(d*Sqrt[a+b*Cos[c+d*x]])*
  Sqrt[(a+b*Cos[c+d*x])/((a-b)*(1-Cos[c+d*x]))]*
  EllipticPi[-1,ArcSin[Cot[(c+d*x)/2]],-Sim[(a+b)/(a-b)]] /;
FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A+B] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]],x_Symbol] :=
  Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]*Tan[(1/2)*(c+d*x)]/d + 
  Int[Sqrt[a+b*Cos[c+d*x]]/(Sqrt[Cos[c+d*x]]*(1+Cos[c+d*x])),x] - 
  Dist[a/2,Int[(1-Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[1/(Sqrt[Cos[c_.+d_.*x_]]*(a_+b_.*Cos[c_.+d_.*x_])),x_Symbol] :=
  2/(d*(a+b))*EllipticPi[Sim[2*b/(a+b)],(c+d*x)/2,2] /;
FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[1/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_.+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=
  2/(d*Sqrt[a+b])*EllipticF[ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;
FreeQ[{a,b,c,d},x] && PositiveQ[b] && PositiveQ[b^2-a^2]


(* ::Code:: *)
Int[1/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=
  Sqrt[-Cos[c+d*x]]/Sqrt[Cos[c+d*x]]*Int[1/(Sqrt[-Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;
FreeQ[{a,b,c,d},x] && NegativeQ[b] && PositiveQ[b^2-a^2]


(* ::Code:: *)
Int[1/(Sqrt[Cos[c_.+d_.*x_]]*Sqrt[a_.+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=
  2*Sqrt[1+Cos[c+d*x]]/(d*Sqrt[a+b*Cos[c+d*x]])*
  Sqrt[(a+b*Cos[c+d*x])/((a+b)*(1+Cos[c+d*x]))]*
  EllipticF[ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[1/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=  -2/(d*Sqrt[a-b])*EllipticF[ArcSin[Cot[(c+d*x)/2]],-Sim[(a+b)/(a-b)]] /;FreeQ[{a,b,c,d},x] && NegativeQ[b] && PositiveQ[b^2-a^2]


(* ::Code:: *)
Int[1/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=  Sqrt[Cos[c+d*x]]/Sqrt[-Cos[c+d*x]]*Int[1/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x] /;FreeQ[{a,b,c,d},x] && PositiveQ[b] && PositiveQ[b^2-a^2]


(* ::Code:: *)
Int[1/(Sqrt[-Cos[c_.+d_.*x_]]*Sqrt[a_+b_.*Cos[c_.+d_.*x_]]),x_Symbol] :=  -2*Sqrt[1-Cos[c+d*x]]/(d*Sqrt[a+b*Cos[c+d*x]])*  Sqrt[(a+b*Cos[c+d*x])/((a-b)*(1-Cos[c+d*x]))]*  EllipticF[ArcSin[Cot[(c+d*x)/2]],-Sim[(a+b)/(a-b)]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[a_+b_.*Cos[c_.+d_.*x_]]/Sqrt[Cos[c_.+d_.*x_]],x_Symbol] :=  Dist[a-b,Int[1/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]] +   Dist[b,Int[(1+Cos[c+d*x])/(Sqrt[Cos[c+d*x]]*Sqrt[a+b*Cos[c+d*x]]),x]] /;FreeQ[{a,b,c,d},x] && NonzeroQ[a^2-b^2]


(* ::Code:: *)
Int[Sqrt[a_+b_.*Cos[c_.+d_.*x_]]/(Sqrt[Cos[c_.+d_.*x_]]*(A_+B_.*Cos[c_.+d_.*x_])),x_Symbol] :=  Sqrt[a+b]/(d*A)*EllipticE[ArcSin[Tan[(c+d*x)/2]],-Sim[(a-b)/(a+b)]] /;FreeQ[{a,b,c,d,A,B},x] && ZeroQ[A-B] && PositiveQ[b] && PositiveQ[b^2-a^2]
